[package]
name = "nvme_driver"
version = "0.1.0"
edition = "2021"
authors = ["Le Chen <lenuulan@gmail.com>", "周睿 <zrufo747@outlook.com>"]
description = "PCI device drivers"


[dependencies]
volatile = "0.3"
lock = { git = "https://github.com/DeathWish5/kernel-sync", rev = "8486b8" }


[dev-dependencies]
bare-test = "0.1"
log = "0.4"

[build-dependencies]
sparreal-macros = "0.0.5"
