[package]
name = "nvme-driver"
version = "0.2.0"
edition = "2021"
authors = ["周睿 <zrufo747@outlook.com>"]
description = "nvme driver"


[dependencies]
tock-registers = "0.9.0"
log = "0.4"
dma-api = "0.1"

[dev-dependencies]
bare-test = "0.1"
pcie = { git = "https://gitee.com/zr233/pcie" , tag = "v0.1.0"}
byte-unit = { version = "5.1.6", default-features = false, features = ["byte"] }

[build-dependencies]
sparreal-macros = "0.0.5"
