[package]
name = "nvme_driver"
version = "0.2.0"
edition = "2021"
authors = ["周睿 <zrufo747@outlook.com>", "Le Chen <lenuulan@gmail.com>"]
description = "nvme driver"


[dependencies]
volatile = "0.3"
lock = { git = "https://github.com/DeathWish5/kernel-sync", rev = "8486b8" }
tock-registers = "0.9.0"
log = "0.4"

[dev-dependencies]
bare-test = "0.1"
pcie = { git = "https://gitee.com/zr233/pcie" }
byte-unit = { version = "5.1.6", default-features = false, features = ["byte"] }

[build-dependencies]
sparreal-macros = "0.0.5"
